### ISSUE TITLE
Rename `pl_devtools` to `lightning_tools`

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/devtools#19]
## 🚀 Feature

See title. Feel free to close if you disagree

**Comment by carmocca** [comment]
Related discussion: https://github.com/Lightning-AI/lightning/pull/14475#discussion_r959737186

**Comment by Borda** [comment]
the package name is already: https://github.com/Lightning-AI/devtools/blob/45ea7c5a594b61d4b264900fc4ed2ff459c76804/setup.py#L28
but the comment above was rather about the package scope not no name in particular

**Comment by carmocca** [comment]
@Borda Why not go for `lightning_tools` directly?

Also, I would not go with `lit`. It's inconsistent with everything else

**Comment by akihironitta** [comment]
+1 for `lightning_tools`.

**Comment by awaelchli** [comment]
`+1 for lightning_tools` if we feel like in the future there will be more than just devtools (maybe docs utils too who knows?)
`+1 for lightning_devtools` if the intention is to make it super focused
